# Site settings
title: ME111 - Laboratório de Estatística
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  samarafk

# Build settings
markdown: kramdown
exclude: ['*.Rmd']
